// DO NOT EDIT. generated by webtyp.com/ormc

package patientdirectory

import (
	"webtyp.com/model"
	"webtyp.com/orm"
)

type Patient struct {
	Id string
	TenantId string
	Rut string
	Name string
	Birthdate string
	Phone string
	Email string
	Address string
	IsActive bool
	UpdatedAt int64
}

func (m *Patient) ModelName() string { return "patient" }

func (m *Patient) Schema() []model.Field { return PatientModel.Fields }

func (m *Patient) Pointers() []any { return []any{&m.Id, &m.TenantId, &m.Rut, &m.Name, &m.Birthdate, &m.Phone, &m.Email, &m.Address, &m.IsActive, &m.UpdatedAt} }

func (m *Patient) IsNil() bool { return m == nil }

func (m *Patient) EncodeFields(w model.FieldWriter) {
	if m.Id != "" { w.String("id", m.Id) }
	w.String("tenant_id", m.TenantId)
	w.String("rut", m.Rut)
	w.String("name", m.Name)
	if m.Birthdate != "" { w.String("birthdate", m.Birthdate) }
	if m.Phone != "" { w.String("phone", m.Phone) }
	if m.Email != "" { w.String("email", m.Email) }
	if m.Address != "" { w.String("address", m.Address) }
	w.Bool("is_active", m.IsActive)
	if m.UpdatedAt != 0 { w.Int("updated_at", m.UpdatedAt) }
}

func (m *Patient) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("id"); ok { m.Id = v }
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("rut"); ok { m.Rut = v }
	if v, ok := r.String("name"); ok { m.Name = v }
	if v, ok := r.String("birthdate"); ok { m.Birthdate = v }
	if v, ok := r.String("phone"); ok { m.Phone = v }
	if v, ok := r.String("email"); ok { m.Email = v }
	if v, ok := r.String("address"); ok { m.Address = v }
	if v, ok := r.Bool("is_active"); ok { m.IsActive = v }
	if v, ok := r.Int("updated_at"); ok { m.UpdatedAt = v }
}

type PatientList []*Patient

func (s *PatientList) Len() int             { return len(*s) }
func (s *PatientList) At(i int) model.Fielder { return (*s)[i] }
func (s *PatientList) Append() model.Fielder  { v := &Patient{}; *s = append(*s, v); return v }
func (s *PatientList) IsNil() bool          { return s == nil }
func (s *PatientList) EncodeFields(_ model.FieldWriter) {}
func (s *PatientList) DecodeFields(_ model.FieldReader) {}

func (m *Patient) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

var Patient_ = struct {
	Id string
	TenantId string
	Rut string
	Name string
	Birthdate string
	Phone string
	Email string
	Address string
	IsActive string
	UpdatedAt string
}{
	Id: "id",
	TenantId: "tenant_id",
	Rut: "rut",
	Name: "name",
	Birthdate: "birthdate",
	Phone: "phone",
	Email: "email",
	Address: "address",
	IsActive: "is_active",
	UpdatedAt: "updated_at",
}

func ReadOnePatient(qb *orm.QB, model *Patient) (*Patient, error) {
	err := qb.ReadOne()
	if err != nil {
		return nil, err
	}
	return model, nil
}

func ReadAllPatient(qb *orm.QB) (PatientList, error) {
	var results PatientList
	err := qb.ReadAll(
		func() model.Model { return &Patient{} },
		func(m model.Model) { results = append(results, m.(*Patient)) },
	)
	return results, err
}

type ListPatientsArgs struct {
	TenantId string
	ActiveOnly bool
	Limit int64
	Offset int64
}

func (m *ListPatientsArgs) ModelName() string { return "list_patients_args" }

func (m *ListPatientsArgs) Schema() []model.Field { return ListPatientsArgsModel.Fields }

func (m *ListPatientsArgs) Pointers() []any { return []any{&m.TenantId, &m.ActiveOnly, &m.Limit, &m.Offset} }

func (m *ListPatientsArgs) IsNil() bool { return m == nil }

func (m *ListPatientsArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.Bool("active_only", m.ActiveOnly)
	w.Int("limit", m.Limit)
	w.Int("offset", m.Offset)
}

func (m *ListPatientsArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.Bool("active_only"); ok { m.ActiveOnly = v }
	if v, ok := r.Int("limit"); ok { m.Limit = v }
	if v, ok := r.Int("offset"); ok { m.Offset = v }
}

type ListPatientsArgsList []*ListPatientsArgs

func (s *ListPatientsArgsList) Len() int             { return len(*s) }
func (s *ListPatientsArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *ListPatientsArgsList) Append() model.Fielder  { v := &ListPatientsArgs{}; *s = append(*s, v); return v }
func (s *ListPatientsArgsList) IsNil() bool          { return s == nil }
func (s *ListPatientsArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *ListPatientsArgsList) DecodeFields(_ model.FieldReader) {}

func (m *ListPatientsArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type GetPatientArgs struct {
	TenantId string
	Id string
}

func (m *GetPatientArgs) ModelName() string { return "get_patient_args" }

func (m *GetPatientArgs) Schema() []model.Field { return GetPatientArgsModel.Fields }

func (m *GetPatientArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *GetPatientArgs) IsNil() bool { return m == nil }

func (m *GetPatientArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *GetPatientArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type GetPatientArgsList []*GetPatientArgs

func (s *GetPatientArgsList) Len() int             { return len(*s) }
func (s *GetPatientArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *GetPatientArgsList) Append() model.Fielder  { v := &GetPatientArgs{}; *s = append(*s, v); return v }
func (s *GetPatientArgsList) IsNil() bool          { return s == nil }
func (s *GetPatientArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *GetPatientArgsList) DecodeFields(_ model.FieldReader) {}

func (m *GetPatientArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type FindPatientByRutArgs struct {
	TenantId string
	Rut string
}

func (m *FindPatientByRutArgs) ModelName() string { return "find_patient_by_rut_args" }

func (m *FindPatientByRutArgs) Schema() []model.Field { return FindPatientByRutArgsModel.Fields }

func (m *FindPatientByRutArgs) Pointers() []any { return []any{&m.TenantId, &m.Rut} }

func (m *FindPatientByRutArgs) IsNil() bool { return m == nil }

func (m *FindPatientByRutArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("rut", m.Rut)
}

func (m *FindPatientByRutArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("rut"); ok { m.Rut = v }
}

type FindPatientByRutArgsList []*FindPatientByRutArgs

func (s *FindPatientByRutArgsList) Len() int             { return len(*s) }
func (s *FindPatientByRutArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *FindPatientByRutArgsList) Append() model.Fielder  { v := &FindPatientByRutArgs{}; *s = append(*s, v); return v }
func (s *FindPatientByRutArgsList) IsNil() bool          { return s == nil }
func (s *FindPatientByRutArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *FindPatientByRutArgsList) DecodeFields(_ model.FieldReader) {}

func (m *FindPatientByRutArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

type DeactivatePatientArgs struct {
	TenantId string
	Id string
}

func (m *DeactivatePatientArgs) ModelName() string { return "deactivate_patient_args" }

func (m *DeactivatePatientArgs) Schema() []model.Field { return DeactivatePatientArgsModel.Fields }

func (m *DeactivatePatientArgs) Pointers() []any { return []any{&m.TenantId, &m.Id} }

func (m *DeactivatePatientArgs) IsNil() bool { return m == nil }

func (m *DeactivatePatientArgs) EncodeFields(w model.FieldWriter) {
	w.String("tenant_id", m.TenantId)
	w.String("id", m.Id)
}

func (m *DeactivatePatientArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("tenant_id"); ok { m.TenantId = v }
	if v, ok := r.String("id"); ok { m.Id = v }
}

type DeactivatePatientArgsList []*DeactivatePatientArgs

func (s *DeactivatePatientArgsList) Len() int             { return len(*s) }
func (s *DeactivatePatientArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *DeactivatePatientArgsList) Append() model.Fielder  { v := &DeactivatePatientArgs{}; *s = append(*s, v); return v }
func (s *DeactivatePatientArgsList) IsNil() bool          { return s == nil }
func (s *DeactivatePatientArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *DeactivatePatientArgsList) DecodeFields(_ model.FieldReader) {}

func (m *DeactivatePatientArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}
